server:
  port: 8080
projectName: File Text Bulk Data Generator
projectVersion: 1.0.0
projectDescription: File Text Bulk Data Generator

springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  override-with-generic-response: false
  paths-to-exclude: /**/api-docs,/swagger-resources/**
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.personal

config-data-external: classpath:resource/config-data-external-definitions.json

